### ISSUE TITLE
Run mdl on specific directory

### ISSUE THREAD

**Issue by mjbear** [bewuethr/mdl-action#34]
Hello @bewuethr ,

What do you think about enhancing the mdl-action by adding an argument for specifying a directory?

Locally I can run `mdl tests` to run against a specific directory that has a group of markdown files.

If the directory argument is not provided, then default to current dir `.`

Thoughts?

I'm game to hack on this if you'll accept a PR! :grinning:

**Comment by bewuethr** [comment]
That should be fairly straightforward: the command is hardcoded to the current directory at

https://github.com/bewuethr/mdl-action/blob/1dd031a5215823fd7540452b53eabc0751c933d3/runmdl#L5-L9

which could be easily replaced with a parameter provided as an input to the action, defaulting to `.`. Happy to look at a PR if you create one!

**Comment by mjbear** [comment]
> which could be easily replaced with a parameter provided as an input to the action, defaulting to `.`. Happy to look at a PR if you create one!

Agreed, it shouldn't be too bad to implement.

Thank you for the support and guidance! :grinning:

**Comment by mjbear** [comment]
@bewuethr 
If I was to use positional shell arguments `$1` then this becomes a problem when the `style-file` isn't specified, but a directory is.

GH Actions [creates env vars for inputs](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs), I might be able to hook into those in the shell script.

Hyphens in shell variables are going to cause an issue so I'll likely have to change `style-file` to `style_file`.

Using underscores instead of hyphens would be a breaking change for anyone using `style-file` so I believe this would be a major version bump. :face_with_peeking_eye: 

Thoughts?

* https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action#creating-an-action-metadata-file
* https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs
* https://github.com/orgs/community/discussions/26938#discussioncomment-3254052

**Comment by bewuethr** [comment]
If you make the new input the first positional parameter (passed in via [`runs.args`](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsargs), like the style file), it'll never be empty because it has a default, and swapping the order of positional parameters is invisible to users of the action, what do you think?

**Comment by mjbear** [comment]
> If you make the new input the first positional parameter (passed in via [`runs.args`](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsargs), like the style file), it'll never be empty because it has a default, and swapping the order of positional parameters is invisible to users of the action, what do you think?

I considered swapping the order.

Yeah, worth a try.

Thank you.

**Comment by bewuethr** [comment]
Actually, I think you wouldn't even have to swap the order. If you have

```yaml
args:
  - ${{ inputs.style-file }}
  - ${{ inputs.diretcory }}
```

and the `style-file` input is empty, an empty string will be passed to `ENTRYPOINT`, and

```sh
stylefile=$1
directory=$2
```

would still work; `stylefile` would just be empty.

**Comment by mjbear** [comment]
> would still work; `stylefile` would just be empty.

@bewuethr

Tested, and yeah it works. Wow.
